### ISSUE TITLE
feature concatenation option

### ISSUE THREAD

**Issue by hytseng0509** [taki0112/DRIT-Tensorflow#1]
Hi,
Thanks for the elegant implementation. 
It seems that you have the incorrect statement about the `--concat` option in [readme](https://github.com/taki0112/DRIT-Tensorflow/blob/master/README.md#tips). It should be:
`True` : for the shape **preserving** translation (winter <-> summer) (default)
`False` : for the shape **variation** translation (cat <-> dog)

**Comment by taki0112** [comment]
I fix it and i add your pytorch code in readme

Thank you

**Comment by hytseng0509** [comment]
Thanks.

**Comment by hytseng0509** [comment]
Thanks!
