### ISSUE TITLE
g_loss divergence 

### ISSUE THREAD

**Issue by junwoopark92** [taki0112/DRIT-Tensorflow#2]
hello

thank you for good implementations

I am training drit for celeba dataset

trainA is black hair and B is brown hair

in training, g_loss  divergence (inf)

please give me a some tip in this case

current args setting is default

thank you

**Comment by taki0112** [comment]
hair change is `shape preserving translation` 
So you use `concat = True`

**Comment by taki0112** [comment]
I'm tested `cat2dog` that is `concat = False`, but didn't g_loss go to infinity...
Does infinity mean `nan`?

**Comment by junwoopark92** [comment]
yeah

I meant the nan value.

This does not happen after lr is halved. (lr = 0.00005)

It's a special case

this is good implementation

thank you

**Comment by unlugi** [comment]
I have this nan problem with another dataset. What is the reason, do you have a guess?
